# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 
  enable: ture
  year: 2015
# style: default | during
  style: default

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: atom.xml

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  # Archives: /archives/
  # Tags: /tags/
  Categories: /categories.html
  About: /about.html
  Message: /message.html
  Links: /links.html

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: cobalt blue

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: false

pjax: false

# LaTeX support (via MathJax)
latex: false

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

# 赞赏
reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# footer 是否显示hexo和主题的信息
footer:
  power-by: false
  theme-info: false

# ===========================================
# Social links Settings
# ===========================================
social:
  email: 
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: 
  weibo:
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# 分析和推送
analytics: false
# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Valine comment https://valine.js.org
valine:
  appid: XtxvAXPwOzM9noIc3eyxi3AS-gzGzoHsz # your leancloud appid
  appkey: yEVQszyxb4bwLuAGU5VHnPR8 # your leancloud appkey
  notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
  verify: true # true/false:verify code
  avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  placeholder: 说点什么吧... # comment box placeholder
  visitor: ture
# Disqus
disqus_shortname:

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

#Wordcount
wordcount:
  enable: ture
  post: ture
  total: ture
  time: ture

# ===========================================
# Version
# ===========================================
version: 2.11.0
